services:
  - type: web
    name: coral-vmms
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_DB
        value: vmms
